# see https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml
[tools]
usage = "latest"
java = "lts"
node = "lts"
#deno = "latest"
bun = "latest"
yarn = "latest"
zig = "latest"
# zig language server:
zls = "latest"
#python = {version='3.12'}  # caused some issues, best continue using system py version for global

[settings]
idiomatic_version_file_enable_tools = []
